[package]
name = "camas"
version = "0.0.1"
edition = "2021"

[dependencies]
derive_builder = "0.20.0"
log = "0.4.21"
nom = "7.1.3"
num-bigint = "0.4.4"
owo-colors = "4.0.0"
termcolor = "1.4.1"

[dev-dependencies]
env_logger = "0.11.3"
owo-colors = "4.0.0"
serial_test = "3.0.0"
