services:
  redis:
    image: redis
    ports:
      - 6379:6379
  gui:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOST=redis
      - FOLDING_CHAR=+
    ports:
      - 8081:8081
